#!/usr/bin/env bash
# This script installs, configures, and starts the Nginx server.
# It begins by updating the package lists for APT.
apt-get update

# Install Nginx with the -y flag for non-interactive installation.
apt-get -y install nginx

# Allow HTTP traffic through the firewall for Nginx.
sudo ufw allow 'Nginx HTTP'

# Create a directory for the web files and set permissions.
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www

# Create a simple 'Hello World!' index file.
echo 'Hello World!' > /var/www/html/index.html

SERVER_CONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files $uri $uri/ =404;
        }
		if (\$request_filename ~ redirect_me){
			rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
		}
}"

# Write the server configuration to the default Nginx configuration file.
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

# Restarting Nginx service
sudo service nginx restart
