#!/usr/bin/env bash
# This script installs, configures, and starts the Nginx server.
# It begins by updating the package lists for APT.
# Install Nginx with the -y flag for non-interactive installation.
# Allow HTTP traffic through the firewall for Nginx.
# Create a directory for the web files and set permissions.
# Create a simple 'Hello World!' index file.
# Write the server configuration to the default Nginx configuration file.
# Restarting Nginx service

apt-get update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
