#!/usr/bin/env bash
# Bash script to install and configure HAproxy as a load balancer.

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

# Backup the original HAproxy configuration file
sudo mv /etc/haproxy/haproxy.cfg.bak
sudo touch /etc/haproxy/haproxy.cfg

# HAproxy configuration
server_config=\
"
frontend load_balancer
        bind *:80
        mode http
        default_backend webservers
backend webservers
        balance roundrobin
        server 520532-web-01 52.23.177.252:80 check
        server 520532-web-02 18.204.7.7:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Ensure HAProxy can be managed via an init script
sudo systemctl enable haproxy
sudo service haproxy restart
