#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  abdel-frontend
        bind *:80
        mode http
        default_backend yonas-backend
backend abdel-backend
        balance roundrobin
        server 520532-web-01 52.23.177.252:80 check
        server 520532-web-02 18.204.7.7:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
