#!/usr/bin/env bash
# Bash script to install and configure HAproxy as a load balancer.

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

# Backup the original HAproxy configuration file
sudo mv /etc/haproxy/haproxy.cfg.bak
sudo touch /etc/haproxy/haproxy.cfg

# HAproxy configuration
server_config=\
"
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend load_balancer
        bind *:80
        mode http
        default_backend webservers

backend webservers
        balance roundrobin
        server 520532-web-01 52.23.177.252:80 check
        server 520532-web-02 18.204.7.7:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Ensure HAProxy can be managed via an init script
sudo systemctl enable haproxy
sudo service haproxy restart
