#!/usr/bin/env bash
# Script for automating correction of configuration issues

# Remove existing symbolic link to prevent duplicate configurations
sudo rm /etc/nginx/sites-enabled/default

# Recreate symbolic link to ensure proper Nginx configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx service to apply the changes
sudo service nginx restart
