#!/usr/bin/env bash

# Continuously writes "I am alive!" to the file /tmp/my_process.
# Pauses for two seconds between each message.

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
