#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays the data sorted by occurrences

awk '{count[$1" "$9]++} END {for (combo in count) print count[combo], combo}' apache-access.log | sort -nr
