#!/usr/bin/env bash
# This script groups and sorts Apache log data by IP and HTTP status code

awk '{freq[$1" "$9]++} END {for (ip_status in freq) print freq[ip_status], ip_status}' apache-access.log | sort -k1,1nr -k2,2
