#!/usr/bin/env bash

# Get the path to the Gunicorn executable
GUNICORN_BIN=$(which gunicorn)

# Check if Gunicorn is installed
if [ -z "$GUNICORN_BIN" ]; then
    echo "Gunicorn is not installed or not found in the PATH."
    exit 1
fi

# Gracefully reload Gunicorn by sending a HUP signal to the master process
echo "Reloading Gunicorn..."
systemctl status gunicorn | grep -oE 'Main PID: [0-9]+' | cut -d ' ' -f3 | xargs kill -HUP

echo "Gunicorn reloaded successfully."
